package com.wickedcoder.wifilens.core.database

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "room",
    foreignKeys = [
        ForeignKey(
            entity = GridPlanEntity::class,
            parentColumns = ["id"],
            childColumns = ["planId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("planId")],
)
/** A named room. [id] is Room's own autogenerated row key, used only by this table; [roomId] is
 * the small app-level integer that [CellType.Floor] cells actually store to say which room they
 * belong to. They're deliberately different: [roomId] is chosen by the app (see `MapViewModel`)
 * and needs to be stable and cheap to embed in every floor cell, not tied to how Room happens to
 * order inserts. */
data class RoomEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val planId: Long,
    val roomId: Int,
    val name: String,
)
